// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFp56Edz8rL2dB3J9Wik8gT807Dq-X1M',
    appId: '1:526752852832:web:8b968b9e825ed03d2f0c05',
    messagingSenderId: '526752852832',
    projectId: 'phase-photo',
    authDomain: 'phase-photo.firebaseapp.com',
    storageBucket: 'phase-photo.appspot.com',
    measurementId: 'G-YJNRCSL6FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLqmoLilCGXW7gOdQj9TjZMDEMHwpB6Y',
    appId: '1:526752852832:android:f1a2c5508b76bebf2f0c05',
    messagingSenderId: '526752852832',
    projectId: 'phase-photo',
    storageBucket: 'phase-photo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVMyfdPTrx7pSBn1B-5PeDdiJHje3XNs',
    appId: '1:526752852832:ios:0da20a95f055097b2f0c05',
    messagingSenderId: '526752852832',
    projectId: 'phase-photo',
    storageBucket: 'phase-photo.appspot.com',
    iosBundleId: 'com.example.phasePhoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAVMyfdPTrx7pSBn1B-5PeDdiJHje3XNs',
    appId: '1:526752852832:ios:95751b1626db67502f0c05',
    messagingSenderId: '526752852832',
    projectId: 'phase-photo',
    storageBucket: 'phase-photo.appspot.com',
    iosBundleId: 'com.example.phasePhoto.RunnerTests',
  );
}
